version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: docker run --rm --privileged multiarch/qemu-user-static:register
    #  - run: docker login --username $DOCKER_USER --password $DOCKER_PASS
     - run: docker build -t chfanghr/docker-opencv-arm:latest .
    #  - run: docker push chfanghr/docker-opencv-arm:latest     